sudo: required
services:
  - docker
language: python
install:
  - pip install -r example/app/requirements.txt
# command to run tests
script:
  - python -m pytest -v example/test/test_app.py
after_success:
  - sh example/travis/deploy_dockerhub.sh
