version: '3'
services:
  flask:
    image: webapp-flask
    environment:
    - encrypted=${encrypted}
    - key=${key}
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
